name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/images/smt.png
    - assets/images/group.png
    - assets/images/bag.png
    - assets/images/search.png
    - assets/images/jam.png
    - assets/images/baju.png
    - assets/images/headdphone.png
    - assets/images/seppatu.png
    - assets/images/bajuu.png
    - assets/images/jam1.png
    - assets/lottie/
