name: slicing_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/group.png
    - assets/images/bag.png
    - assets/images/search.png
    - assets/images/jam.png
    - assets/images/baju.png
    - assets/images/headdphone.png
    - assets/images/seppatu.png
